name: Generate static and deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./src

      - name: Test with pytest
        run: pytest -svvx .
        working-directory: ./src

      - name: Generate static
        run: python generate.py
        working-directory: ./src

      - name: Deploy to Server
        run: |
          echo ${{ secrets.KEY }} > deployer_id_rsa
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install openssh-client
          sudo systemctl start ssh
          scp -i deployer_id_rsa -P ${{ secrets.PORT }} ./out/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/C:/www/lpr-ekb/
